addSbtPlugin("org.scalameta"           % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("org.scoverage"           % "sbt-scoverage"       % "1.8.2")
addSbtPlugin("com.lightbend.akka.grpc" % "sbt-akka-grpc"       % "2.1.6")
addSbtPlugin("io.spray"                % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.github.sbt"          % "sbt-native-packager" % "1.9.7")
addSbtPlugin("com.lightbend.sbt"       % "sbt-javaagent"       % "0.1.6")
addSbtPlugin("io.gatling"              % "gatling-sbt"         % "4.1.5")
addSbtPlugin("io.kamon"                % "sbt-kanela-runner"   % "2.0.14")
